export { default as Hashtag } from './Hashtag.svg'
export { default as Speaker } from './Speaker.svg'
export { default as Zoom } from './Zoom.svg'
export { default as Hamburger } from './Hamburger.svg'
export { default as LabelOne } from './LabelOne.svg'
export { default as Leaf } from './Leaf.svg'
export { default as Leaf2 } from './Leaf2.svg'
export { default as LabelDiamond } from './LabelDiamond.svg'