import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const champBlack = localFont({
  src: './Champ-Black.woff2',
  variable: '--font-champBlack'
})

const aeonik = localFont({
  src: './Aeonik-Regular.ttf',
  variable: '--font-aeonik'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-brand-black mx-auto ${champBlack.variable} ${aeonik.className}`}
      >
        {children}
      </body>
    </html>
  );
}
